[project]
name = "openpe"
version = "0.1.0.dev2"
description = "Open Python Package for simple access to Peruvian Open Data"
authors = [{name = "Ivan", email = "your.email@example.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"