name: Publish to TestPyPI

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: testpypi  # Optional: for added control
    permissions:
      id-token: write  # Required for Trusted Publishers

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install build tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to TestPyPI
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/