name: Publish to PyPI

# Trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi  # Optional: for added control
    permissions:
      id-token: write  # Required for Trusted Publishers

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Install build tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # Build the package
      - name: Build package
        run: python -m build

      # Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload dist/* --verbose